# Generated by Django 3.0 on 2019-12-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_auto_20191209_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('TD', 'To Do'), ('IP', 'In Progress'), ('D', 'Done')], max_length=2),
        ),
    ]
