# Generated by Django 3.0 on 2019-12-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0006_auto_20191209_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
